const devinettesLocales = [
  { riddle: "Je suis partout mais on ne me voit pas. Qui suis-je ?", answer: "air" },
  { riddle: "Je peux ouvrir sans force. Qui suis-je ?", answer: "clé" },
  { riddle: "Je tombe du ciel sans faire mal. Qui suis-je ?", answer: "pluie" },
  { riddle: "Je suis ton reflet, mais je ne suis pas toi. Qui suis-je ?", answer: "miroir" },
  { riddle: "Je suis là quand tu ne parles pas. Qui suis-je ?", answer: "silence" },
  { riddle: "Je suis chaud sans feu. Qui suis-je ?", answer: "vent" },
  { riddle: "Je suis là quand la lumière s’éteint. Qui suis-je ?", answer: "ombre" },
  { riddle: "Je cache les contours du monde. Qui suis-je ?", answer: "brume" },
  { riddle: "Je suis toujours devant toi, mais tu ne peux jamais me voir. Qui suis-je ?", answer: "Le futur" },
  { riddle: "Je suis léger comme une plume, mais même le plus fort des hommes ne peut me tenir plus de 5 minutes. Qui suis-je ?", answer: "Le souffle" },
  { riddle: "Qu'est-ce qui est plein de trous mais peut encore contenir de l'eau ?", answer: "Une éponge" },
  { riddle: "Je peux être cassé sans jamais être touché. Qui suis-je ?", answer: "Une promesse" },
  { riddle: "Je suis souvent servi mais je ne mange jamais. Qui suis-je ?", answer: "Un plat" },
  { riddle: "Plus j'en prends, plus je laisse derrière moi. Qui suis-je ?", answer: "Des pas" },
  { riddle: "Qu'est-ce qui est plus grand que la Terre et qui ne pèse rien ?", answer: "Le ciel" },
  { riddle: "Je suis parfois jaune et je brille dans le ciel. Qui suis-je ?", answer: "Le soleil" },
  { riddle: "Je suis toujours devant vous mais je ne peux pas être vu. Qui suis-je ?", answer: "Le temps" },
  { riddle: "Qu'est-ce qui a des dents mais ne peut pas mordre ?", answer: "Un peigne" },
  { riddle: "Je suis invisible, mais vous pouvez me sentir. Qui suis-je ?", answer: "Le vent" },
  { riddle: "Je suis souvent mis dans une boîte, mais je ne suis jamais un objet. Qui suis-je ?", answer: "Un secret" },
  { riddle: "Je suis une source de chaleur, mais je ne suis pas un feu. Qui suis-je ?", answer: "Le soleil" },
  { riddle: "Qu'est-ce qui peut être cassé sans qu'on le touche ?", answer: "Le silence" },
  { riddle: "Je suis une clé qui ne peut ouvrir aucune porte. Qui suis-je ?", answer: "Une clé USB" },
  { riddle: "Qu'est-ce qui est toujours en avance, mais n'arrête jamais ?", answer: "horloge" },
  { riddle: "Je n'ai ni bouche, ni nez, mais je parle quand même. Qui suis-je ?", answer: "Un écho" },
  { riddle: "Qu'est-ce qui est souvent vu mais rarement entendu ?", answer: "La lune" },
  { riddle: "Qu'est-ce qui est toujours devant nous mais qu'on ne peut jamais voir ?", answer: "Le futur" },
  { riddle: "Plus il y en a, moins vous en voyez. Qu'est-ce ?", answer: "L'obscurité" },
  { riddle: "Qu'est-ce qui monte mais ne descend jamais ?", answer: "L'âge" },
  { riddle: "Je suis pris avant vous, mais vous ne pouvez jamais me prendre après. Qui suis-je ?", answer: "Une photo" },
  { riddle: "Je suis souvent long mais je n'ai pas de fin. Qui suis-je ?", answer: "Une histoire" },
  { riddle: "Qu'est-ce qui a des dents mais ne mord jamais ?", answer: "Un peigne" },
  { riddle: "Je suis toujours dans la poche, mais je ne suis jamais vu. Qui suis-je ?", answer: "argent" },
  { riddle: "Je suis grand quand je suis jeune, et petit quand je suis vieux. Qui suis-je ?", answer: "Une bougie" },
  { riddle: "Je suis tout petit et très souvent présent dans la cuisine, qui suis-je ?", answer: "Le sel" },
  { riddle: "Je suis invisible mais j'ai une grande force. Qui suis-je ?", answer: "Le vent" },
  { riddle: "Je suis blanc, je tombe du ciel et je ne fonds pas dans l'eau. Qui suis-je ?", answer: "La neige" },
  { riddle: "J'ai des dents mais ne mange jamais. Qui suis-je ?", answer: "Le peigne" },
  { riddle: "Je commence la nuit et je termine le matin. Qui suis-je ?", answer: "La lettre N" },
  { riddle: "J'ai une longue trompe et de grandes oreilles. Qui suis-je ?", answer: "éléphant" },
  { riddle: "Je me lève et me couche sans jamais faire de bruit. Qui suis-je ?", answer: "Le soleil" },
  { riddle: "J'ai un dos et quatre pieds, mais je ne marche pas. Qui suis-je ?", answer: "La chaise" },
  { riddle: "Plus on en prend, plus on en laisse derrière soi. Qui suis-je ?", answer: "Les pas" },
  { riddle: "J'ai des clés mais n'ouvre aucune porte. Qui suis-je ?", answer: "La partition de musique" },
  { riddle: "Qu'est-ce qui est toujours devant toi mais que tu ne peux pas voir ?", answer: "L'avenir" },
  { riddle: "Je peux être cassé, mais sans être touché. Qui suis-je ?", answer: "Le secret" },
  { riddle: "Qui a quatre pattes le matin, deux à midi et trois le soir ?", answer: "L'homme" },
  { riddle: "Qu'est-ce qui est plein de trous, mais retient l'eau ?", answer: "Une éponge" },
  { riddle: "Je peux être vert, mais je ne suis pas une plante ; je suis dur, mais je ne suis pas de la pierre. Qui suis-je ?", answer: "Le verre" },
  { riddle: "Qu'est-ce qui devient plus mouillé au fur et à mesure qu'il sèche ?", answer: "Une serviette" },
  { riddle: "Quel est le comble pour un électricien ?", answer: "D'avoir des ampoules aux pieds" },
  { riddle: "J'ai des villes, mais pas de maisons ; des montagnes, mais pas d'arbres ; et de l'eau, mais pas de poissons. Qui suis-je ?", answer: "Une carte" },
  { riddle: "J'ai deux aiguilles, mais ne couds jamais. Qui suis-je ?", answer: "Une horloge" },
  { riddle: "Qu'est-ce qui se casse dès qu'on le nomme ?", answer: "Le silence" },
  { riddle: "J'ai un œil, mais je ne vois pas. Qui suis-je ?", answer: "Une aiguille" },
  { riddle: "J'ai une tête et une queue, mais pas de corps. Qui suis-je ?", answer: "Une pièce de monnaie" },
  { riddle: "Quel mot de 5 lettres devient plus court quand on lui ajoute deux lettres ?", answer: "Court" },
  { riddle: "J'ai des racines que personne ne voit, je suis plus haut que les arbres. Qui suis-je ?", answer: "Une montagne" },
  { riddle: "J'ai un lit, mais ne dors jamais. Qui suis-je ?", answer: "Une rivière" },
  { riddle: "On me dévore sans jamais me manger. Qui suis-je ?", answer: "Un livre" },
  { riddle: "On m'ouvre, on me referme, mais je n'entre jamais. Qui suis-je ?", answer: "Le frigo" },
  { riddle: "J'ai deux bras mais pas de mains. Qui suis-je ?", answer: "Un manteau" },
  { riddle: "Je suis entouré d'anneaux, mais je n'ai pas de doigt. Qui suis-je ?", answer: "Saturne" },
  { riddle: "Si on m'appelle, je ne peux plus parler. Qui suis-je ?", answer: "L'écho" },
  { riddle: "J'appartiens à toi, mais les autres m'utilisent plus que toi. Qui suis-je ?", answer: "Ton prénom"},
  { riddle: "Je deviens plus gros quand on me vide. Qui suis-je ?", answer: "Un trou" },
  { riddle: "Qu'est-ce qui court sans jamais avoir de jambes ?", answer: "L'eau" },
  { riddle: "Je suis fait pour être mangé, mais on ne me mange jamais. Qui suis-je ?", answer: "L'assiette" },
  { riddle: "Je suis toujours en avance, mais j'arrive toujours en retard. Qui suis-je ?", answer: "Le futur" },
  { riddle: "J'ai un cou, mais je n'ai pas de tête. Qui suis-je ?", answer: "La bouteille" },
  { riddle: "Que faut-il pour allumer une bougie ?", answer: "Le feu" },
  { riddle: "Quand on me jette, je monte ; quand on me lâche, je descends. Qui suis-je ?", answer: "Une balle rebondissante" },
  { riddle: "Je m'assieds souvent mais je n'ai jamais de siège. Qui suis-je ?", answer: "Les fesses" },
  { riddle: "On me trouve dans un four, mais je ne suis pas un plat. Qui suis-je ?", answer: "La lettre F" },
  { riddle: "Plus c'est chaud, plus je suis frais. Qui suis-je ?", answer: "Le pain" },
  { riddle: "J'ai des clés mais pas de serrures, j'ai un espace mais pas de pièce. Qui suis-je ?", answer: "Le clavier" },
  { riddle: "Quel animal est le plus vieux ?", answer: "Le zèbre" },
  { riddle: "Je suis là quand on ferme les yeux. Qui suis-je ?", answer: "Le sommeil" },
  { riddle: "Si tu me regardes, tu vois ce que tu as fait. Qui suis-je ?", answer: "Le reflet" },
  { riddle: "Je peux voyager partout dans le monde en restant dans mon coin. Qui suis-je ?", answer: "Le timbre" },
  { riddle: "Qu'est-ce qui est noir quand on l'achète, rouge quand on l'utilise et gris quand on le jette ?", answer: "Le charbon de bois" },
  { riddle: "J'ai des piquants mais je ne suis pas un hérisson, je suis souvent rouge ou blanc. Qui suis-je ?", answer: "La rose" },
  { riddle: "Je me remplis le jour et me vide la nuit. Qui suis-je ?", answer: "La lune" },
  { riddle: "J'ai un chapeau, mais pas de tête. Qui suis-je ?", answer: "Le champignon" },
  { riddle: "Que fait un chat quand il a mal ?", answer: "MIAOU" },
  { riddle: "Je te suis partout, mais je ne suis personne. Qui suis-je ?", answer: "Ton ombre" },
  { riddle: "Je n'ai pas de poumons, mais j'ai besoin d'air. Qui suis-je ?", answer: "Le pneu" },
  { riddle: "Je coupe la tête et la queue, mais j'utilise un couteau pour cuisiner. Qui suis-je ?", answer: "Le cuisinier" },
  { riddle: "Que dit-on à un chien sans pattes ?", answer: "\"Tu es où ?\"" },
  { riddle: "Je suis souvent porté, mais je n'ai pas d'épaules. Qui suis-je ?", answer: "La cravate" },
  { riddle: "Qu'est-ce qui peut briser le verre sans faire de bruit ?", answer: "Le vent" },
  { riddle: "Je deviens plus petit à chaque fois que je prends un bain. Qui suis-je ?", answer: "Le savon" },
  { riddle: "J'ai une langue, mais je ne peux pas parler. Qui suis-je ?", answer: "La chaussure" },
  { riddle: "Qu'est-ce qui se passe une fois par minute, deux fois par moment et jamais en mille ans ?", answer: "La lettre M" },
  { riddle: "Plus il y a de monde dedans, plus il est léger. Qui suis-je ?", answer: "L'ascenseur" },
  { riddle: "J'ai des notes, mais je ne fais pas de musique. Qui suis-je ?", answer: "Le cahier" },
  { riddle: "Qu'est-ce qu'on jette quand on veut s'en servir et qu'on garde quand on ne veut plus l'utiliser ?", answer: "L'ancre" },
  { riddle: "Je peux retenir le lait, mais ne suis pas un seau. Qui suis-je ?", answer: "Une passoire" },
  { riddle: "Je ne peux pas respirer, mais j'ai un nez ; je n'ai pas de peau, mais j'ai des rides. Qui suis-je ?", answer: "Le piment" },
  { riddle: "Je ne suis pas vivant, mais je peux mourir. Qui suis-je ?", answer: "Le feu" },
  { riddle: "Quel est l'animal le plus silencieux ?", answer: "La mouette" },
  { riddle: "J'ai des lèvres, mais je ne peux pas embrasser. Qui suis-je ?", answer: "La tasse" },
  { riddle: "J'ai des touches, mais je ne joue pas de piano. Qui suis-je ?", answer: "interrupteur" },
  { riddle: "J'ai des larmes, mais je ne pleure jamais. Qui suis-je ?", answer: "oignon" },
  { riddle: "Que doit-on casser pour pouvoir l'utiliser ?", answer: "Un œuf" }

  
];
